// 自動生成ファイル - 直接編集しないこと
// backend/models.py と backend/params.py から生成:
//   python tools/gen_js_tables.py

export const DEFAULT_PROFILE = "RS02";

export const PROFILES = {
  "RS00": {
    "key": "RS00",
    "label": "RobStride 00",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -33.0,
    "v_max": 33.0,
    "t_min": -14.0,
    "t_max": 14.0,
    "kp_max": 500.0,
    "kd_max": 5.0,
    "i_max": 16.0,
    "note": "電流レンジ ±16A / トルク上限 14Nm はマニュアルのパラメータ表に記載あり"
  },
  "RS01": {
    "key": "RS01",
    "label": "RobStride 01",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -44.0,
    "v_max": 44.0,
    "t_min": -17.0,
    "t_max": 17.0,
    "kp_max": 500.0,
    "kd_max": 5.0,
    "i_max": null,
    "note": ""
  },
  "RS02": {
    "key": "RS02",
    "label": "RobStride 02",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -44.0,
    "v_max": 44.0,
    "t_min": -17.0,
    "t_max": 17.0,
    "kp_max": 500.0,
    "kd_max": 5.0,
    "i_max": null,
    "note": ""
  },
  "RS03": {
    "key": "RS03",
    "label": "RobStride 03",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -20.0,
    "v_max": 20.0,
    "t_min": -60.0,
    "t_max": 60.0,
    "kp_max": 5000.0,
    "kd_max": 100.0,
    "i_max": null,
    "note": ""
  },
  "RS04": {
    "key": "RS04",
    "label": "RobStride 04",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -15.0,
    "v_max": 15.0,
    "t_min": -120.0,
    "t_max": 120.0,
    "kp_max": 5000.0,
    "kd_max": 100.0,
    "i_max": null,
    "note": ""
  },
  "RS05": {
    "key": "RS05",
    "label": "RobStride 05",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -50.0,
    "v_max": 50.0,
    "t_min": -5.5,
    "t_max": 5.5,
    "kp_max": 500.0,
    "kd_max": 5.0,
    "i_max": null,
    "note": ""
  },
  "RS06": {
    "key": "RS06",
    "label": "RobStride 06",
    "p_min": -12.57,
    "p_max": 12.57,
    "v_min": -50.0,
    "v_max": 50.0,
    "t_min": -36.0,
    "t_max": 36.0,
    "kp_max": 5000.0,
    "kd_max": 100.0,
    "i_max": null,
    "note": ""
  }
};

export const PARAMS = [
  {
    "index": 28677,
    "indexHex": "0x7005",
    "name": "run_mode",
    "label": "運転モード",
    "type": "uint8",
    "rw": "rw",
    "writable": true,
    "group": "mode",
    "unit": "",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": [
      {
        "value": 0,
        "label": "0: 運動制御 (Operation)"
      },
      {
        "value": 1,
        "label": "1: 位置 PP (台形加減速)"
      },
      {
        "value": 2,
        "label": "2: 速度 (Speed)"
      },
      {
        "value": 3,
        "label": "3: 電流 (Current)"
      },
      {
        "value": 5,
        "label": "5: 位置 CSP (速度制限付き)"
      }
    ],
    "note": "モード切替は必ず停止状態で行うこと"
  },
  {
    "index": 28678,
    "indexHex": "0x7006",
    "name": "iq_ref",
    "label": "電流指令 Iq",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "command",
    "unit": "A",
    "min": "@i",
    "max": "@i",
    "default": null,
    "step": 0.1,
    "choices": null,
    "note": "電流モード用"
  },
  {
    "index": 28682,
    "indexHex": "0x700A",
    "name": "spd_ref",
    "label": "速度指令",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "command",
    "unit": "rad/s",
    "min": "@v",
    "max": "@v",
    "default": null,
    "step": 0.1,
    "choices": null,
    "note": "速度モード用"
  },
  {
    "index": 28694,
    "indexHex": "0x7016",
    "name": "loc_ref",
    "label": "位置指令",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "command",
    "unit": "rad",
    "min": -12.57,
    "max": 12.57,
    "default": null,
    "step": 0.01,
    "choices": null,
    "note": "位置モード用"
  },
  {
    "index": 28683,
    "indexHex": "0x700B",
    "name": "limit_torque",
    "label": "トルク制限",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "limit",
    "unit": "Nm",
    "min": 0,
    "max": "@t+",
    "default": null,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28695,
    "indexHex": "0x7017",
    "name": "limit_spd",
    "label": "速度制限 (CSP)",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "limit",
    "unit": "rad/s",
    "min": 0,
    "max": "@v+",
    "default": null,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28696,
    "indexHex": "0x7018",
    "name": "limit_cur",
    "label": "電流制限 (速度/位置)",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "limit",
    "unit": "A",
    "min": 0,
    "max": "@i+",
    "default": null,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28688,
    "indexHex": "0x7010",
    "name": "cur_kp",
    "label": "電流ループ Kp",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 10,
    "default": 0.17,
    "step": 0.001,
    "choices": null,
    "note": ""
  },
  {
    "index": 28689,
    "indexHex": "0x7011",
    "name": "cur_ki",
    "label": "電流ループ Ki",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 10,
    "default": 0.012,
    "step": 0.001,
    "choices": null,
    "note": ""
  },
  {
    "index": 28692,
    "indexHex": "0x7014",
    "name": "cur_filt_gain",
    "label": "電流フィルタゲイン",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 1.0,
    "default": 0.1,
    "step": 0.001,
    "choices": null,
    "note": ""
  },
  {
    "index": 28702,
    "indexHex": "0x701E",
    "name": "loc_kp",
    "label": "位置ループ Kp",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 1000,
    "default": 40,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28703,
    "indexHex": "0x701F",
    "name": "spd_kp",
    "label": "速度ループ Kp",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 1000,
    "default": 6,
    "step": 0.01,
    "choices": null,
    "note": ""
  },
  {
    "index": 28704,
    "indexHex": "0x7020",
    "name": "spd_ki",
    "label": "速度ループ Ki",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 100,
    "default": 0.02,
    "step": 0.001,
    "choices": null,
    "note": ""
  },
  {
    "index": 28705,
    "indexHex": "0x7021",
    "name": "spd_filt_gain",
    "label": "速度フィルタゲイン",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "gain",
    "unit": "",
    "min": 0,
    "max": 1.0,
    "default": 0.1,
    "step": 0.001,
    "choices": null,
    "note": ""
  },
  {
    "index": 28706,
    "indexHex": "0x7022",
    "name": "acc_rad",
    "label": "加速度 (速度モード)",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "profile",
    "unit": "rad/s^2",
    "min": 0,
    "max": 1000,
    "default": 20,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28708,
    "indexHex": "0x7024",
    "name": "vel_max",
    "label": "最大速度 (PP)",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "profile",
    "unit": "rad/s",
    "min": 0,
    "max": "@v+",
    "default": 10,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28709,
    "indexHex": "0x7025",
    "name": "acc_set",
    "label": "加速度 (PP)",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "profile",
    "unit": "rad/s^2",
    "min": 0,
    "max": 1000,
    "default": 10,
    "step": 0.1,
    "choices": null,
    "note": ""
  },
  {
    "index": 28710,
    "indexHex": "0x7026",
    "name": "EPScan_time",
    "label": "能動送信周期",
    "type": "uint16",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "",
    "min": 1,
    "max": 1000,
    "default": 1,
    "step": 1,
    "choices": null,
    "note": "1 = 10ms、以降 +1 ごとに 5ms 増加"
  },
  {
    "index": 28712,
    "indexHex": "0x7028",
    "name": "canTimeout",
    "label": "CAN タイムアウト閾値",
    "type": "uint32",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "",
    "min": 0,
    "max": 4000000,
    "default": 0,
    "step": 1,
    "choices": null,
    "note": "20000 = 1s、0 で無効。超過するとモータは Reset モードへ"
  },
  {
    "index": 28713,
    "indexHex": "0x7029",
    "name": "zero_sta",
    "label": "原点フラグ",
    "type": "uint8",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "",
    "min": null,
    "max": null,
    "default": 0,
    "step": null,
    "choices": [
      {
        "value": 0,
        "label": "0: 電源投入時 0〜2π"
      },
      {
        "value": 1,
        "label": "1: 電源投入時 -π〜π"
      }
    ],
    "note": "変更後は通信タイプ 22 で保存が必要"
  },
  {
    "index": 28714,
    "indexHex": "0x702A",
    "name": "damper",
    "label": "ダンパースイッチ",
    "type": "uint8",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "",
    "min": null,
    "max": null,
    "default": 0,
    "step": null,
    "choices": [
      {
        "value": 0,
        "label": "0: 電源断時のダンピング有効 (既定)"
      },
      {
        "value": 1,
        "label": "1: ダンピング無効"
      }
    ],
    "note": ""
  },
  {
    "index": 28715,
    "indexHex": "0x702B",
    "name": "add_offset",
    "label": "原点オフセット",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "rad",
    "min": -12.57,
    "max": 12.57,
    "default": 0,
    "step": 0.01,
    "choices": null,
    "note": "現在の原点を (現在位置 + offset) へずらす"
  },
  {
    "index": 28697,
    "indexHex": "0x7019",
    "name": "mechPos",
    "label": "出力軸機械角",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "rad",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": ""
  },
  {
    "index": 28698,
    "indexHex": "0x701A",
    "name": "iqf",
    "label": "Iq (フィルタ後)",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "A",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": ""
  },
  {
    "index": 28699,
    "indexHex": "0x701B",
    "name": "mechVel",
    "label": "出力軸速度",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "rad/s",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": ""
  },
  {
    "index": 28700,
    "indexHex": "0x701C",
    "name": "VBUS",
    "label": "バス電圧",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "V",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": ""
  },
  {
    "index": 12310,
    "indexHex": "0x3016",
    "name": "mechPos_measured",
    "label": "実測位置",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "rad",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": "公式 Python SDK の MEASURED_POSITION"
  },
  {
    "index": 12311,
    "indexHex": "0x3017",
    "name": "mechVel_measured",
    "label": "実測速度",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "rad/s",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": "公式 Python SDK の MEASURED_VELOCITY"
  },
  {
    "index": 12332,
    "indexHex": "0x302C",
    "name": "torque_fdb",
    "label": "実測トルク",
    "type": "float",
    "rw": "r",
    "writable": false,
    "group": "monitor",
    "unit": "Nm",
    "min": null,
    "max": null,
    "default": null,
    "step": null,
    "choices": null,
    "note": "公式 Python SDK の MEASURED_TORQUE"
  },
  {
    "index": 8197,
    "indexHex": "0x2005",
    "name": "mechOffset",
    "label": "磁気エンコーダ角オフセット",
    "type": "float",
    "rw": "rw",
    "writable": true,
    "group": "config",
    "unit": "rad",
    "min": -7,
    "max": 7,
    "default": null,
    "step": 1e-06,
    "choices": null,
    "note": "キャリブレーション値。通常は変更しないこと"
  }
];

export const GROUP_LABELS = {
  "mode": "運転モード",
  "command": "指令値",
  "limit": "制限値",
  "gain": "制御ゲイン",
  "profile": "動作プロファイル",
  "config": "動作設定 (保存対象)",
  "monitor": "モニタ (読み出し専用)"
};

export const RUN_MODE_CHOICES = [
  {
    "value": 0,
    "label": "0: 運動制御 (Operation)"
  },
  {
    "value": 1,
    "label": "1: 位置 PP (台形加減速)"
  },
  {
    "value": 2,
    "label": "2: 速度 (Speed)"
  },
  {
    "value": 3,
    "label": "3: 電流 (Current)"
  },
  {
    "value": 5,
    "label": "5: 位置 CSP (速度制限付き)"
  }
];

// レンジのプレースホルダ (機種プロファイルで実行時に解決する)
export const PLACEHOLDERS = {
  "V_LIM": "@v",
  "V_POS": "@v+",
  "T_POS": "@t+",
  "I_LIM": "@i",
  "I_POS": "@i+"
};
